### ISSUE TITLE
ERROR: HTTP error 404 while getting https://github.com/CW4RR10R/pyrogram/archive/asyncio.zip

### ISSUE THREAD

**Issue by susukntl7** [Omkar47/AutoLeecher#6]
Collecting https://github.com/CW4RR10R/pyrogram/archive/asyncio.zip (from -r requirements.txt (line 5))
  ERROR: HTTP error 404 while getting https://github.com/CW4RR10R/pyrogram/archive/asyncio.zip
  ERROR: Could not install requirement https://github.com/CW4RR10R/pyrogram/archive/asyncio.zip (from -r requirements.txt (line 5)) because of error 404 Client Error: Not Found for url: https://github.com/CW4RR10R/pyrogram/archive/asyncio.zip
ERROR: Could not install requirement https://github.com/CW4RR10R/pyrogram/archive/asyncio.zip (from -r requirements.txt (line 5)) because of HTTP error 404 Client Error: Not Found for url: https://github.com/CW4RR10R/pyrogram/archive/asyncio.zip for URL https://github.com/CW4RR10R/pyrogram/archive/asyncio.zip
The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

**Comment by Omkar47** [comment]
Fixed
